- docs/specs/API.md
- docs/specs/API_details.md
> add API list

- README.md
- docs/specs/API.md
- docs/specs/API_details.md
> add details of API

- docs/specs/Internal.md
> add internal API specs

- handler/ping.go
- middleware/logger.go
- middleware/middleware.go
> add logrus module

- models/bucket.go
- models/dataserver.go
- models/error.go
- models/group.go
- models/object.go
> init data struct

- main.go
- middleware/logger.go
- middleware/middleware.go
- utils/setting/setting.go
> edit settings and logger init function

- docs/specs/API_details.md
- docs/specs/Internal.md
- models/bucket.go
- models/error.go
- models/group.go
This PR contains following changes of API and related change of data struct:
1. All json item name starts with lowercase letter
2. Adjust struct of group
> adjust API and data struct

- conf/runtime.yaml.example
- main.go
- models/dataserver.go
- models/dataserver_test.go
- utils/db/db.go
- utils/db/factory/factory.go
- utils/db/mysql/mysql.go
- utils/db/redis/redis.go
- utils/setting/setting.go
- web/web.go
> init SQL/KV database connection & adjust settings

- handler/internal/dataserver.go
- models/dataserver.go
- router/router.go
- web/web.go
> implment dataserver status recieve API

- .gitignore
- cmd/web.go
- main.go
- middleware/logger.go
- middleware/middleware.go
- setting/setting.go
- web/web.go
> change the location of setting folder

- handler/service.go
- models/bucket.go
- models/bucket_test.go
- models/dataserver_test.go
- models/user.go
- router/router.go
- setting/setting.go
- utils/db/factory/factory.go
- utils/db/mysql/mysql.go
- utils/db/redis/redis.go
- web/web.go
> implement get all buckets API & add ORM associations

- handler/bucket.go
- models/bucket.go
- models/bucket_test.go
- models/user.go
> fix one-to-one association and preload query

- .gitignore
- cmd/allinone.go
- conf/allinone.yaml
- main.go
- setting/objectserver.go
> add allinone mode

- cmd/allinone.go
- handler/object.go
- models/object.go
> optimze the allinone mode and upload function

- handler/inner/dataserver.go
When registering data servers, if any of them already exists in the database, return a 409 error(conflict).
> Before registering data servers, check if they exist in the db.

- handler/inner/dataserver.go
Updates:
`POST /internal/v1/dataserver`:
- When registering new data servers, check if any one of the given servers exists. 
- Caching the data server info in goroutine, making the codes concurrent
> API updates and optimization

- README.md
- cmd/allinone.go
- dataserver/spy_server.c
> add quick start in README & remove extra println information

- handler/object.go
> change the way of read object content to steaming reading

- cmd/dataserver.go
- cmd/objectserver.go
- cmd/registrationcenter.go
- cmd/web.go
- conf/dataserver.yaml.example
- main.go
- router/router.go
- web/web.go
> split arkor into two roles:objectserver, registration center

- cmd/allinone.go
- conf/runtime.yaml.example
- handler/inner/dataserver.go
- middleware/logger.go
- middleware/middleware.go
- setting/setting.go
- utils/db/mysql/mysql.go
> add log level setting & optimze log output
